### ISSUE TITLE
Pull Request for Typescript Branch

### ISSUE THREAD

**Issue by lukewis** [joefazz/react-native-web-starter#1]
Hi @joefazz, thanks for the awesome repo!  I've forked your repo and created a typescript branch, but I'm not sure how to submit a pull request since the branch doesn't yet exist in your repo (I don't want my branch to be "merged" into any of yours, I just want to have the new branch "added" to your repo).  Is it possible for you to create an "empty" typescript branch, and then I'll submit a pull request against that?

**Comment by joefazz** [comment]
Hi @lukewis ! Yes definitely I will do this as soon as I get to a laptop. Thanks for contributing!

**Comment by joefazz** [comment]
https://github.com/joefazz/react-native-web-starter/tree/typescript
