### ISSUE TITLE
get jest running?

### ISSUE THREAD

**Issue by nickmeldrum** [joefazz/react-native-web-starter#11]
Hey Joe,

I'm having a go at using this repo as the base for a new project, and I noticed you have a "todo" of "get jest working" - I was going to have a look at this now (and of course if I fix it will submit a PR back to you.) - did you have any clues/ thoughts to start me off?

**Comment by joefazz** [comment]
Hi Nick!

I actually don't have a lot of experience with Jest so a PR would be greatly appreciated otherwise I'd just be trying to stab in the dark.
