### ISSUE TITLE
expo update

### ISSUE THREAD

**Issue by brody2consult** [joefazz/react-native-web-starter#14]
Using expo pre-28 seems to gives me the the following kind of failure:

```
$ yarn start-native
yarn run v1.15.2
$ react-native-scripts start
9:16:43 AM: Unable to start server
See https://git.io/v5vcn for more information, either install watchman or run the following snippet:
  sudo sysctl -w kern.maxfiles=5242880
  sudo sysctl -w kern.maxfilesperproc=524288
        
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I think it would be ideal to upgrade to the latest version ref: <https://docs.expo.io/versions/v32.0.0/workflow/upgrading-expo-sdk-walkthrough/>

**Comment by joefazz** [comment]
I can't upgrade to latest because RNW requires RN version 0.55 which this expo version points too. When the next RNW release is published with RN 0.59 support I will update expo.

In the meantime you can get around this by directly starting the expo cli with `expo start`
