### ISSUE TITLE
trying to add native library and fail to compile 

### ISSUE THREAD

**Issue by obiwankenoobi** [joefazz/react-native-web-starter#22]
Hello. I tried to build the app with one native library (react-native-calendars) and it throw an error : 

```
Failed to compile.

./node_modules/react-native-calendars/src/calendar-list/index.js
Module parse failed: Unexpected token (17:19)
You may need an appropriate loader to handle this file type.
| 
| class CalendarList extends Component {
|   static propTypes = {
|     ...Calendar.propTypes,
|
```

I guess it's a webpack thing. Any idea what can I do or where to config my webpack? 

Thank you!

**Comment by joefazz** [comment]
https://github.com/wix/react-native-calendars/issues/2 might help?

**Comment by obiwankenoobi** [comment]
> [wix/react-native-calendars#2](https://github.com/wix/react-native-calendars/issues/2) might help?

Not really. I need to manually config webpack to make it work. But I can't see any option to eject the web part of the project. Am I right or am I missing something and I am able to config webpack somehow?

## EDIT

At the end I did `react-native eject` so I could config the webpack manually so the issue can be closed now
