### ISSUE TITLE
Upgrade to Expo SDK v30

### ISSUE THREAD

**Issue by AryanJ-NYC** [joefazz/react-native-web-starter#25]
As explained in #14, this starter cannot be upgraded to the latest Expo.

However, according to [this blog post](https://blog.expo.io/expo-sdk-v31-0-0-is-now-available-cad6d0463f49), SDK release v30.0.0 was based on React Native 0.55. This means that this starter can be successfully upgraded to SDK v30.0.0.

(FWIW, I can create a PR to do this a bit later)

**Comment by joefazz** [comment]
Thanks for finding this and making your PRs I appreciate it :smile:
