### ISSUE TITLE
Add Hot Module Reloading

### ISSUE THREAD

**Issue by gianpaj** [joefazz/react-native-web-starter#6]
i believe we should integrate it with [react-hot-loader](https://github.com/gaearon/react-hot-loader).

This will enable much faster development than a full page refresh (on the web)

**Comment by joefazz** [comment]
If you run `yarn web` then it runs it the same way Create React App runs which I was under the impression uses react-hot-loader. I'll look into it.

**Comment by joefazz** [comment]
If you want react-hot-loader to work it requires more changes than I'm comfortable offering in just a boilerplate, such as ejecting from CRA so I'm going to close this and leave it as a decision you can make after you clone the repo
