### ISSUE TITLE
 Quick question about debugging Typescript version

### ISSUE THREAD

**Issue by vongohren** [joefazz/react-native-web-starter#8]
This web version is pretty hell to debug in the console because first transpiled es6 and ts, and the through react native modules. Or is it anything one can do to better that?

**Comment by brody2consult** [comment]
I found a few things that might help:

- https://code.visualstudio.com/docs/typescript/typescript-debugging
- https://blog.fullstacktraining.com/debugging-typescript-in-the-browser/
- https://medium.com/@dupski/debug-typescript-in-vs-code-without-compiling-using-ts-node-9d1f4f9a94a
- https://www.google.com/search?q=debug+transpiled+typescript

**Comment by joefazz** [comment]
I should get around to doing this but I don't have the time currently. If you can get it working please do send a PR :)

**Comment by AryanJ-NYC** [comment]
@vongohren Do you have a sample repository or sample code that is "hell to debug" using this starter? I'd love to recreate what you see and try to create a PR for this issue.

**Comment by vongohren** [comment]
@AryanJ-NYC hey, no sorry, I believe its all cleaned up unfortunately. This is a bit too long ago for my repos and local code.

But I believe it was pretty basic initialization with typescript.
It is clear when you do remote debugging and try to do breakpoints or understand what line the code points to. 

Sorry I could not help more :(
