### ISSUE TITLE
Hangs on starting packager Typescript version

### ISSUE THREAD

**Issue by vongohren** [joefazz/react-native-web-starter#9]
I try starting native and android, but it just keeps hanging on starting packager.
Is there anything I need to do to make it available.
Since your using expo, I guess there should pop up a qr code or something.

When i quit it it says stopped packager.

**Comment by joefazz** [comment]
I'll look into this sorry for late response I've been busy for the past few months.

**Comment by vongohren** [comment]
Great 😁

**Comment by AryanJ-NYC** [comment]
I was able to re-create this in the `typescript` branch. `react-native-scripts` did not work to launch the app. `expo` launches the app successfully. I created a PR that switches the start scripts to use `expo` and removes the unused `react-native-scripts` package.

**Comment by vongohren** [comment]
But what about when you want to eject?

**Comment by AryanJ-NYC** [comment]
I've added an `eject-expo` script that ejects without a problem (at least on my local machine).

Thought I have the feeling this is not what you meant...

**Comment by vongohren** [comment]
Im not sure, I cant really remember the contex of this task:(
